add arm64/v9 matching vectors
containerd/platforms pull request #12
Opened 2024-06-15 01:37 UTC by tonistiigi

Allow arm64/v9 to fall back to arm64/v8

cc @tianon

2024-06-17 22:33 UTC, tianon commented
I agree with this change, but it's also significantly more complicated than this (thanks Arm! :sob:) -- see https://github.com/golang/go/issues/60905#issuecomment-1611867608 :see_no_evil:

See also https://github.com/containerd/containerd/issues/10022 and https://github.com/containerd/platforms/pull/8 (which is an attempt to more correctly implement the complexity of arm64 variants that I somehow missed previously :disappointed:)

2024-10-20 21:58 UTC, AkihiroSuda approved these changes

2024-10-21 03:06 UTC, tianon requested changes
Adding an explicit NACK; this needs to be something more complicated (like #8 which I need to get back to reviewing :see_no_evil:)

2024-10-31 23:22 UTC, tonistiigi commented
closing this in favor of #8

2024-10-31 23:22 UTC, closed without merging